name: codephile
description: Codephile.

publish_to: 'none'

version: 1.0.0+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.1
  charts_flutter: ^0.12.0
  dio: ^4.0.4
  dropdown_search: ^5.0.3
  equatable: ^2.0.3
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_messaging: ^13.0.4
  firebase_remote_config: ^2.0.19
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^11.0.1
  flutter_native_splash: ^2.1.6
  flutter_native_timezone: ^2.0.0
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  flutter_typeahead: ^4.1.1
  flutter_web_browser: ^0.17.0
  freezed_annotation: ^2.1.0
  get: ^4.6.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.0.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.11
  rxdart: ^0.27.3
  sentry_flutter: ^6.2.2

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.1.4
  mocktail:

flutter:
  uses-material-design: true
  assets:
    - assets/app/icons/
    - assets/app/images/
    - assets/app/images/platforms/
    - assets/app/illustrations/

flutter_native_splash:
  android: true
  color: "#FFFFFF"
  image: "assets/launch/splash.png"
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/launch/adaptive_foreground.png"
  image_path_ios: "assets/launch/launch_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launch/adaptive_foreground.png"
